title: AI Agents Technical Blog
baseurl: "/ai-tech-site"
url: "https://leonas5555.github.io"
collections:
  articles:
    output: true
    permalink: /articles/:slug/
  code_samples:
    output: false
defaults:
  - scope:
      path: "_articles"
    values:
      layout: "post"
  - scope:
      path: "code_samples"
    values:
      layout: "code"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude only directories that shouldn't be processed
exclude:
  - code_samples
  - drafts
  - scripts
  - .venv
  - .env
  - .env.example
  - README.md
  - inventory.yaml
  - inventory_publish.yaml
  - inventory_draft.yaml
  - linkedin
  - previews
  - .cursor
  - .github
  - vendor
  - .bundle
  - .jekyll-cache

sass_dir: _sass

kramdown:
  parse_block_html: true
  input: GFM 